services:
  php:
    build:
      context: .
    volumes:
      - ./:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: